name: crime_map
description: Crime Map

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^2.2.0
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  flutter_bloc: ^7.0.1
  flutter_hooks: ^0.17.0
  flutter_signin_button: ^2.0.0
  fluttertoast: ^8.0.7
  freezed_annotation: ^0.14.2
  geocoding: ^2.0.0
  geolocator: ^7.0.3
  get_it: ^7.2.0
  google_maps_flutter: ^2.0.6
  google_maps_place_picker: ^2.0.0-nullsafety.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_sign_in: ^5.0.5
  image_picker: ^0.8.2
  injectable: ^1.4.1
  json_annotation: ^4.0.1
  kt_dart: ^0.9.1
  path: ^1.8.0
  path_provider: ^2.0.2
  place_picker: ^0.9.19-nullsafety
  rxdart: ^0.27.1
  tuple: ^2.0.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.3
  lint: ^1.5.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/crime_map.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/gifs/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
